// Generated by scripts/generate-catalog.mjs. Do not edit by hand.
import type { CatalogItem } from "../types.js";

export const generatedCatalog: CatalogItem[] = [
  {
    "name": "ABS",
    "category": "math",
    "displayName": "绝对值",
    "description": "绝对值",
    "usage": "ABS(X) 返回X的绝对值。",
    "params": [
      "X"
    ],
    "examples": [
      "ABS(-34) 返回34。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "ACOS",
    "category": "math",
    "displayName": "反余弦",
    "description": "反余弦",
    "usage": "ACOS(X) 返回X的反余弦值。",
    "params": [
      "X"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "ADVANCE",
    "category": "market",
    "displayName": "上涨家数",
    "description": "上涨家数",
    "usage": "ADVANCE (本函数仅对大盘有效)",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "ALIGN0",
    "category": "drawProperty",
    "displayName": "对齐 0",
    "description": "绘图文字或图标对齐属性 ALIGN0。",
    "usage": "ALIGN0",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "ALIGN1",
    "category": "drawProperty",
    "displayName": "对齐 1",
    "description": "绘图文字或图标对齐属性 ALIGN1。",
    "usage": "ALIGN1",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "ALIGN2",
    "category": "drawProperty",
    "displayName": "对齐 2",
    "description": "绘图文字或图标对齐属性 ALIGN2。",
    "usage": "ALIGN2",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "ALIGN3",
    "category": "drawProperty",
    "displayName": "对齐 3",
    "description": "绘图文字或图标对齐属性 ALIGN3。",
    "usage": "ALIGN3",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "ALIGN4",
    "category": "drawProperty",
    "displayName": "对齐 4",
    "description": "绘图文字或图标对齐属性 ALIGN4。",
    "usage": "ALIGN4",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "ALIGN5",
    "category": "drawProperty",
    "displayName": "对齐 5",
    "description": "绘图文字或图标对齐属性 ALIGN5。",
    "usage": "ALIGN5",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "AMO",
    "category": "market",
    "displayName": "成交额",
    "description": "成交金额，通达信公式中常用 AMO 表示。",
    "usage": "AMO",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "AMOUNT",
    "category": "market",
    "displayName": "成交额",
    "description": "成交额",
    "usage": "AMOUNT",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "ASIN",
    "category": "math",
    "displayName": "反正弦",
    "description": "反正弦",
    "usage": "ASIN(X) 返回X的反正弦值。",
    "params": [
      "X"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "ASKPRICE",
    "category": "market",
    "displayName": "委卖价",
    "description": "委卖价",
    "usage": "ASKPRICE(N) N取1—3。",
    "params": [
      "N"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "ASKVOL",
    "category": "market",
    "displayName": "委卖量",
    "description": "委卖量",
    "usage": "ASKVOL(N) N取1—3。",
    "params": [
      "N"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "ATAN",
    "category": "math",
    "displayName": "反正切",
    "description": "反正切",
    "usage": "ATAN(X) 返回X的反正切值。",
    "params": [
      "X"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "AVEDEV",
    "category": "statistics",
    "displayName": "平均绝对方差",
    "description": "平均绝对方差",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "BACKSET",
    "category": "reference",
    "displayName": "向前赋值",
    "description": "向前赋值",
    "usage": "BACKSET(X,N) 若X非0,则将当前位置到N周期前的数值设为1。",
    "params": [
      "X",
      "N"
    ],
    "examples": [
      "BACKSET(CLOSE>OPEN,2) 若收阳则将该周期及前一周期数值设为1,否则为0。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "BARSCOUNT",
    "category": "reference",
    "displayName": "有效数据周期数",
    "description": "有效数据周期数",
    "usage": "BARSCOUNT(X) 第一个有效数据到当前的天数。",
    "params": [
      "X"
    ],
    "examples": [
      "BARSCOUNT(CLOSE) 对于日线数据取得上市以来总交易日数,对于分笔成交取得当日成交笔数,对于1分钟线取得当日交易分钟数。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "BARSLAST",
    "category": "reference",
    "displayName": "上一次条件成立位置",
    "description": "上一次条件成立位置",
    "usage": "BARSLAST(X) 上一次X不为0到现在的天数。",
    "params": [
      "X"
    ],
    "examples": [
      "BARSLAST(CLOSE/REF(CLOSE,1)>=1.1) 表示上一个涨停板到当前的周期数。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "BARSLASTCOUNT",
    "category": "reference",
    "displayName": "连续成立周期数",
    "description": "统计条件连续成立的周期数。",
    "usage": "BARSLASTCOUNT(X)",
    "params": [
      "X"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "BARSSINCE",
    "category": "reference",
    "displayName": "第一个条件成立位置",
    "description": "第一个条件成立位置",
    "usage": "BARSSINCE(X) 第一次X不为0到现在的天数。",
    "params": [
      "X"
    ],
    "examples": [
      "BARSSINCE(HIGH>10) 表示股价超过10元时到当前的周期数。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "BARSSINCEN",
    "category": "reference",
    "displayName": "指定窗口内首次成立位置",
    "description": "返回指定窗口内条件成立到当前的周期位置。",
    "usage": "BARSSINCEN(COND,N)",
    "params": [
      "COND",
      "N"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "BETWEEN",
    "category": "math",
    "displayName": "介于",
    "description": "介于",
    "usage": "BETWEEN(A,B,C) 表示A处于B和C之间时返回1,否则返回0。",
    "params": [
      "A",
      "B",
      "C"
    ],
    "examples": [
      "BETWEEN(CLOSE,MA(CLOSE,10),MA(CLOSE,5))表示收盘价介于5日均线和10日均线之间。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "BIDPRICE",
    "category": "market",
    "displayName": "委买价",
    "description": "委买价",
    "usage": "BIDPRICE(N) N取1—3。",
    "params": [
      "N"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "BIDVOL",
    "category": "market",
    "displayName": "委买量",
    "description": "委买量",
    "usage": "BIDVOL(N) N取1—3。",
    "params": [
      "N"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "BLOCKSETNUM",
    "category": "crossSection",
    "displayName": "板块股票个数",
    "description": "板块股票个数",
    "usage": "BLOCKSETNUM(板块名称) 返回该板块股票个数。",
    "params": [
      "板块名称"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "BUYVOL",
    "category": "market",
    "displayName": "主动性买盘",
    "description": "主动性买盘",
    "usage": "BUYVOL 当本笔成交为主动性买盘时,其数值等于成交量,否则为0。",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "C",
    "category": "market",
    "displayName": "收盘价",
    "description": "收盘价",
    "usage": "C",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "CAPITAL",
    "category": "finance",
    "displayName": "流通股本",
    "description": "流通股本",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "CEILING",
    "category": "math",
    "displayName": "向上舍入",
    "description": "向上舍入",
    "usage": "CEILING(A) 返回沿A数值增大方向最接近的整数。",
    "params": [
      "A"
    ],
    "examples": [
      "CEILING(12.3) 求得13,CEILING(-3.5)求得-3。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "CIRCLEDOT",
    "category": "drawProperty",
    "displayName": "画小圆圈线",
    "description": "画小圆圈线",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "CLOSE",
    "category": "market",
    "displayName": "收盘价",
    "description": "收盘价",
    "usage": "CLOSE",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "CODELIKE",
    "category": "reference",
    "displayName": "代码匹配",
    "description": "判断证券代码是否匹配指定前缀或模式。",
    "usage": "CODELIKE(TEXT)",
    "params": [
      "TEXT"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "COLOR",
    "category": "color",
    "displayName": "自定义色",
    "description": "自定义色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORBLACK",
    "category": "color",
    "displayName": "画黑色",
    "description": "画黑色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORBLUE",
    "category": "color",
    "displayName": "画蓝色",
    "description": "画蓝色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORBROWN",
    "category": "color",
    "displayName": "画棕色",
    "description": "画棕色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORCYAN",
    "category": "color",
    "displayName": "画青色",
    "description": "画青色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORGRAY",
    "category": "color",
    "displayName": "画深灰色",
    "description": "画深灰色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORGREEN",
    "category": "color",
    "displayName": "画绿色",
    "description": "画绿色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORLIBLUE",
    "category": "color",
    "displayName": "画淡蓝色",
    "description": "画淡蓝色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORLICYAN",
    "category": "color",
    "displayName": "画淡青色",
    "description": "画淡青色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORLIGRAY",
    "category": "color",
    "displayName": "画淡灰色",
    "description": "画淡灰色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORLIGREEN",
    "category": "color",
    "displayName": "画淡绿色",
    "description": "画淡绿色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORLIMAGENTA",
    "category": "color",
    "displayName": "画淡洋红色",
    "description": "画淡洋红色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORLIRED",
    "category": "color",
    "displayName": "画淡红色",
    "description": "画淡红色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORMAGENTA",
    "category": "color",
    "displayName": "画洋红色",
    "description": "画洋红色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORRED",
    "category": "color",
    "displayName": "画红色",
    "description": "画红色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORRGB",
    "category": "colorFunction",
    "displayName": "RGB 颜色函数",
    "description": "按函数参数指定颜色。",
    "usage": "COLORRGB(R,G,B)",
    "params": [
      "R",
      "G",
      "B"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "COLORSTICK",
    "category": "color",
    "displayName": "画彩色柱状线",
    "description": "画彩色柱状线",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORWHITE",
    "category": "color",
    "displayName": "画白色",
    "description": "画白色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COLORYELLOW",
    "category": "color",
    "displayName": "画黄色",
    "description": "画黄色",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "CON2STR",
    "category": "string",
    "displayName": "数值转字符串",
    "description": "按指定小数位把数值转换为字符串。",
    "usage": "CON2STR(X,N)",
    "params": [
      "X",
      "N"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "CONST",
    "category": "reference",
    "displayName": "取值设为常数",
    "description": "取值设为常数",
    "usage": "CONST(A) 取A最后的值为常量.",
    "params": [
      "A"
    ],
    "examples": [
      "CONST(INDEXC)表示取大盘现价。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COS",
    "category": "math",
    "displayName": "余弦",
    "description": "余弦",
    "usage": "COS(X) 返回X的余弦值。",
    "params": [
      "X"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COST",
    "category": "pattern",
    "displayName": "成本分布",
    "description": "成本分布",
    "usage": "COST(10),表示10%获利盘的价格是多少,即有10%的持仓量在该价格以下,其余90%在该价格以上,为套牢盘。",
    "params": [
      "10"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COSTEX",
    "category": "pattern",
    "displayName": "区间成本",
    "description": "区间成本",
    "usage": "COSTEX(CLOSE,REF(CLOSE)),表示近两日收盘价格间筹码的成本,例如返回10表示区间成本为20元。",
    "params": [
      "CLOSE",
      "REF(CLOSE"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "COUNT",
    "category": "reference",
    "displayName": "统计",
    "description": "统计",
    "usage": "COUNT(X,N) 统计N周期中满足X条件的周期数,若N=0则从第一个有效值开始。",
    "params": [
      "X",
      "N"
    ],
    "examples": [
      "COUNT(CLOSE>OPEN,20) 表示统计20周期内收阳的周期数。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "CROSS",
    "category": "logic",
    "displayName": "上穿",
    "description": "上穿",
    "usage": "CROSS(A,B) 表示当A从下方向上穿过B时返回1,否则返回0。",
    "params": [
      "A",
      "B"
    ],
    "examples": [
      "CROSS(MA(CLOSE,5),MA(CLOSE,10)) 表示5日均线与10日均线交金叉。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "CROSSDOT",
    "category": "drawProperty",
    "displayName": "画小叉线",
    "description": "画小叉线",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "DATE",
    "category": "time",
    "displayName": "日期",
    "description": "日期",
    "usage": "DATE 例如函数返回1000101,表示2000年1月1日。",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "DAY",
    "category": "time",
    "displayName": "日期",
    "description": "日期",
    "usage": "DAY 函数返回有效值范围为(1-31)。",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "DECLINE",
    "category": "market",
    "displayName": "下跌家数",
    "description": "下跌家数",
    "usage": "DECLINE (本函数仅对大盘有效)",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "DEVSQ",
    "category": "statistics",
    "displayName": "数据偏差平方和",
    "description": "数据偏差平方和",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "DMA",
    "category": "reference",
    "displayName": "动态移动平均",
    "description": "动态移动平均",
    "usage": "DMA(X,A) 求X的动态移动平均。",
    "params": [
      "X",
      "A"
    ],
    "examples": [
      "DMA(CLOSE,VOL/CAPITAL) 表示求以换手率作平滑因子的平均价。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "DOWNNDAY",
    "category": "logic",
    "displayName": "连跌",
    "description": "连跌",
    "usage": "DOWNNDAY(CLOSE,M) 表示连跌M个周期。",
    "params": [
      "CLOSE",
      "M"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "DRAWBAND",
    "category": "drawing",
    "displayName": "绘制彩带",
    "description": "在两条曲线或数值之间绘制彩带。",
    "usage": "DRAWBAND(VAL1,COLOR1,VAL2,COLOR2)",
    "params": [
      "VAL1",
      "COLOR1",
      "VAL2",
      "COLOR2"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "DRAWICON",
    "category": "drawing",
    "displayName": "绘制图标",
    "description": "绘制图标",
    "usage": "DRAWICON(COND,PRICE,TYPE),当COND条件满足时,在PRICE位置画TYPE号图标。",
    "params": [
      "COND",
      "PRICE",
      "TYPE"
    ],
    "examples": [
      "DRAWICON(CLOSE>OPEN,LOW,1) 表示当收阳时在最低价位置画1号图标。图标一共有九个,图形如附图。序号,最下面的是“1”号,最上面的是“9”号。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "DRAWKLINE",
    "category": "drawing",
    "displayName": "绘制K线",
    "description": "绘制K线",
    "usage": "DRAWKLINE(HIGH,OPEN,LOW,CLOSE) 以HIGH为最高价,OPEN为开盘价,LOW为最低,CLOSE收盘画K线。",
    "params": [
      "HIGH",
      "OPEN",
      "LOW",
      "CLOSE"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "DRAWLINE",
    "category": "drawing",
    "displayName": "绘制直线段",
    "description": "绘制直线段",
    "usage": "DRAWLINE(COND1,PRICE1,COND2,PRICE2,EXPAND)",
    "params": [
      "COND1",
      "PRICE1",
      "COND2",
      "PRICE2",
      "EXPAND"
    ],
    "examples": [
      "DRAWLINE(HIGH>=HHV(HIGH,20),HIGH,LOW<=LLV(LOW,20),LOW,1) 表示在创20天新高与创20天新低之间画直线并且向右延长。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "DRAWNULL",
    "category": "reference",
    "displayName": "无效数",
    "description": "无效数",
    "usage": "DRAWNULL",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "DRAWTEXT",
    "category": "drawing",
    "displayName": "显示文字",
    "description": "显示文字",
    "usage": "DRAWTEXT(COND,PRICE,TEXT),当COND条件满足时,在PRICE位置书写文字TEXT。",
    "params": [
      "COND",
      "PRICE",
      "TEXT"
    ],
    "examples": [
      "DRAWTEXT(CLOSE/OPEN>1.08,LOW,'大阳线')表示当日涨幅大于8%时在最低价位置显示'大阳线'字样。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "DRAWTEXT_FIX",
    "category": "drawing",
    "displayName": "固定位置文字",
    "description": "在图形固定位置显示文字。",
    "usage": "DRAWTEXT_FIX(COND,X,Y,TYPE,TEXT)",
    "params": [
      "COND",
      "X",
      "Y",
      "TYPE",
      "TEXT"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "DYNAINFO",
    "category": "dynamicQuote",
    "displayName": "动态行情函数",
    "description": "",
    "usage": "",
    "params": [],
    "examples": [
      "DYNAINFO(3) 前收盘价",
      "DYNAINFO(4) 今开",
      "DYNAINFO(5) 最高"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "EMA",
    "category": "reference",
    "displayName": "异同移动平均",
    "description": "异同移动平均",
    "usage": "EMA(X,M) X的M日异同移动平均。",
    "params": [
      "X",
      "M"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "EVERY",
    "category": "logic",
    "displayName": "一直存在",
    "description": "一直存在",
    "usage": "EVERY(CLOSE>OPEN,10) 表示前10日内一直阳线。",
    "params": [
      "CLOSE>OPEN",
      "10"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "EXIST",
    "category": "logic",
    "displayName": "存在",
    "description": "存在",
    "usage": "EXIST(CLOSE>OPEN,10) 表示前10日内存在着阳线。",
    "params": [
      "CLOSE>OPEN",
      "10"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "EXP",
    "category": "math",
    "displayName": "指数",
    "description": "指数",
    "usage": "EXP(X) e的X次幂。",
    "params": [
      "X"
    ],
    "examples": [
      "EXP(CLOSE) 返回e的CLOSE次幂。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "EXPMA",
    "category": "reference",
    "displayName": "加权移动平均",
    "description": "加权移动平均",
    "usage": "EXPMA(X,M) X的M日加权移动平均。",
    "params": [
      "X",
      "M"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "EXPMEMA",
    "category": "reference",
    "displayName": "加权平滑平均",
    "description": "加权平滑平均",
    "usage": "EXPMEMA(X,M) X的M日加权平滑平均。",
    "params": [
      "X",
      "M"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "FILTER",
    "category": "reference",
    "displayName": "过滤",
    "description": "过滤",
    "usage": "FILTER(X,N) X满足条件后,删除其后N周期内的数据置为0。",
    "params": [
      "X",
      "N"
    ],
    "examples": [
      "FILTER(CLOSE>OPEN,5) 查找阳线,5天内再次出现的阳线不被记录在内。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "FINANCE",
    "category": "finance",
    "displayName": "财务函数",
    "description": "",
    "usage": "",
    "params": [],
    "examples": [
      "FINANCE(1) 总股本(万股)",
      "FINANCE(2) `！、,D`！BB、股(万股)",
      "FINANCE(3) 发起人法人股(万股)"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "FINVALUE",
    "category": "finance",
    "displayName": "财务扩展字段",
    "description": "读取财务扩展字段，具体字段含义依通达信版本而定。",
    "usage": "FINVALUE(N)",
    "params": [
      "N"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "FLOOR",
    "category": "math",
    "displayName": "向下舍入",
    "description": "向下舍入",
    "usage": "FLOOR(A) 返回沿A数值减小方向最接近的整数。",
    "params": [
      "A"
    ],
    "examples": [
      "FLOOR(12.3) 求得12,FLOOR(-3.5)求得-4。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "FORCAST",
    "category": "statistics",
    "displayName": "线性回归预测值",
    "description": "线性回归预测值",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "FROMOPEN",
    "category": "time",
    "displayName": "分钟",
    "description": "分钟",
    "usage": "FROMOPEN 返回当前时刻距开盘有多长时间,单位为分钟。",
    "params": [],
    "examples": [
      "FROMOPEN 当前时刻为早上十点,则返回31。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "GPJYVALUE",
    "category": "finance",
    "displayName": "股本/交易扩展数据",
    "description": "读取股东、交易或股本扩展数据，具体口径依版本而定。",
    "usage": "GPJYVALUE(A,B,C)",
    "params": [
      "A",
      "B",
      "C"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "H",
    "category": "market",
    "displayName": "最高价",
    "description": "最高价",
    "usage": "H",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "HHV",
    "category": "reference",
    "displayName": "最高值",
    "description": "最高值",
    "usage": "HHV(X,N) 求N周期内X最高值,N=0则从第一个有效值开始。",
    "params": [
      "X",
      "N"
    ],
    "examples": [
      "HHV(HIGH,30) 表示求30日最高价。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "HHVBARS",
    "category": "reference",
    "displayName": "上一高点位置",
    "description": "上一高点位置",
    "usage": "HHVBARS(X,N) 求N周期内X最高值到当前周期数,N=0表示从第一个有效值开始统计。",
    "params": [
      "X",
      "N"
    ],
    "examples": [
      "HHVBARS(HIGH,0) 求得历史新高到到当前的周期数。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "HIGH",
    "category": "market",
    "displayName": "最高价",
    "description": "最高价",
    "usage": "HIGH",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "HOD",
    "category": "statistics",
    "displayName": "高值排序",
    "description": "返回指定值在窗口内的高值排序或位置，具体语义依通达信版本而定。",
    "usage": "HOD(X,N)",
    "params": [
      "X",
      "N"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "HORCALC",
    "category": "crossSection",
    "displayName": "多股统计",
    "description": "多股统计",
    "usage": "HORCALC(板块名称,数据项,计算方式,权重)",
    "params": [
      "板块名称",
      "数据项",
      "计算方式",
      "权重"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "HOUR",
    "category": "time",
    "displayName": "小时",
    "description": "小时",
    "usage": "HOUR 函数返回有效值范围为(0-23),对于日线及更长的分析周期值为0。",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "IF",
    "category": "arithmetic",
    "displayName": "逻辑判断",
    "description": "逻辑判断",
    "usage": "IF(X,A,B) 若X不为0则返回A,否则返回B。",
    "params": [
      "X",
      "A",
      "B"
    ],
    "examples": [
      "IF(CLOSE>OPEN,HIGH,LOW)表示该周期收阳则返回最高值,否则返回最低值。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "IFF",
    "category": "arithmetic",
    "displayName": "逻辑判断",
    "description": "逻辑判断",
    "usage": "IFF(X,A,B) 若X不为0则返回A,否则返回B。",
    "params": [
      "X",
      "A",
      "B"
    ],
    "examples": [
      "IFF(CLOSE>OPEN,HIGH,LOW) 表示该周期收阳则返回最高值,否则返回最低值。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "IFN",
    "category": "arithmetic",
    "displayName": "逻辑判断",
    "description": "逻辑判断",
    "usage": "IFN(X,A,B) 若X不为0则返回B,否则返回A。",
    "params": [
      "X",
      "A",
      "B"
    ],
    "examples": [
      "IFN(CLOSE>OPEN,HIGH,LOW) 表示该周期收阴则返回最高值,否则返回最低值。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "INDEXA",
    "category": "index",
    "displayName": "返回大盘成交额",
    "description": "返回大盘成交额",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "INDEXADV",
    "category": "index",
    "displayName": "返回上涨家数",
    "description": "返回上涨家数",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "INDEXC",
    "category": "index",
    "displayName": "返回大盘收盘价",
    "description": "返回大盘收盘价",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "INDEXDEC",
    "category": "index",
    "displayName": "返回下跌家数",
    "description": "返回下跌家数",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "INDEXH",
    "category": "index",
    "displayName": "返回大盘最高价",
    "description": "返回大盘最高价",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "INDEXL",
    "category": "index",
    "displayName": "返回大盘最低价",
    "description": "返回大盘最低价",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "INDEXO",
    "category": "index",
    "displayName": "返回大盘开盘价",
    "description": "返回大盘开盘价",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "INDEXV",
    "category": "index",
    "displayName": "返回大盘成交量",
    "description": "返回大盘成交量",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "INTPART",
    "category": "math",
    "displayName": "取整",
    "description": "取整",
    "usage": "INTPART(A) 返回沿A绝对值减小方向最接近的整数。",
    "params": [
      "A"
    ],
    "examples": [
      "INTPART(12.3) 求得12,INTPART(-3.5)求得-3。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "ISBUYORDER",
    "category": "market",
    "displayName": "主动性买单",
    "description": "主动性买单",
    "usage": "ISBUYORDER 当本笔成交为主动性买盘时,返回1,否则为0。",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "ISLASTBAR",
    "category": "market",
    "displayName": "最后一根 K 线",
    "description": "当前周期是否为最后一根 K 线。",
    "usage": "ISLASTBAR",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "ISSELLORDER",
    "category": "market",
    "displayName": "主动性卖单",
    "description": "主动性卖单",
    "usage": "ISSELLORDER 当本笔成交为主动性卖盘时,返回1,否则为0。",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "L",
    "category": "market",
    "displayName": "最低价",
    "description": "最低价",
    "usage": "L",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "L2_AMO",
    "category": "level2",
    "displayName": "L2 金额",
    "description": "读取 Level-2 分档买卖金额数据。",
    "usage": "L2_AMO(TYPE,SIDE)",
    "params": [
      "TYPE",
      "SIDE"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "L2_VOL",
    "category": "level2",
    "displayName": "L2 成交量",
    "description": "读取 Level-2 分档买卖成交量数据。",
    "usage": "L2_VOL(TYPE,SIDE)",
    "params": [
      "TYPE",
      "SIDE"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "L2_VOLNUM",
    "category": "level2",
    "displayName": "L2 笔数",
    "description": "读取 Level-2 分档买卖笔数数据。",
    "usage": "L2_VOLNUM(TYPE,SIDE)",
    "params": [
      "TYPE",
      "SIDE"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "LARGEINTRDVOL",
    "category": "level2",
    "displayName": "大单流入量",
    "description": "大单或主力流入成交量。",
    "usage": "LARGEINTRDVOL",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "LARGEOUTTRDVOL",
    "category": "level2",
    "displayName": "大单流出量",
    "description": "大单或主力流出成交量。",
    "usage": "LARGEOUTTRDVOL",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "LAST",
    "category": "logic",
    "displayName": "持续存在",
    "description": "持续存在",
    "usage": "LAST(X,A,B)A>B,表示从前A日到前B日一直满足X条件。若A为0,表示从第一天开始,B为0,表示到最后日止。",
    "params": [
      "X",
      "A",
      "B"
    ],
    "examples": [
      "LAST(CLOSE>OPEN,10,5) 表示从前10日到前5日内一直阳线。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "LINESTICK",
    "category": "drawProperty",
    "displayName": "同时画出柱状线和指标线",
    "description": "同时画出柱状线和指标线",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "LINETHICK",
    "category": "drawProperty",
    "displayName": "线型粗细",
    "description": "线型粗细",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "LINETHICK1",
    "category": "drawProperty",
    "displayName": "线宽 1",
    "description": "线型粗细 1。",
    "usage": "LINETHICK1",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "LINETHICK2",
    "category": "drawProperty",
    "displayName": "线宽 2",
    "description": "线型粗细 2。",
    "usage": "LINETHICK2",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "LINETHICK3",
    "category": "drawProperty",
    "displayName": "线宽 3",
    "description": "线型粗细 3。",
    "usage": "LINETHICK3",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "LINETHICK4",
    "category": "drawProperty",
    "displayName": "线宽 4",
    "description": "线型粗细 4。",
    "usage": "LINETHICK4",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "LINETHICK5",
    "category": "drawProperty",
    "displayName": "线宽 5",
    "description": "线型粗细 5。",
    "usage": "LINETHICK5",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "LINETHICK6",
    "category": "drawProperty",
    "displayName": "线宽 6",
    "description": "线型粗细 6。",
    "usage": "LINETHICK6",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "LINETHICK7",
    "category": "drawProperty",
    "displayName": "线宽 7",
    "description": "线型粗细 7。",
    "usage": "LINETHICK7",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "LINETHICK8",
    "category": "drawProperty",
    "displayName": "线宽 8",
    "description": "线型粗细 8。",
    "usage": "LINETHICK8",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "LINETHICK9",
    "category": "drawProperty",
    "displayName": "线宽 9",
    "description": "线型粗细 9。",
    "usage": "LINETHICK9",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "LLV",
    "category": "reference",
    "displayName": "最低值",
    "description": "最低值",
    "usage": "LLV(X,N) 求N周期内X最低值,N=0则从第一个有效值开始。",
    "params": [
      "X",
      "N"
    ],
    "examples": [
      "LLV(LOW,0) 表示求历史最低价。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "LLVBARS",
    "category": "reference",
    "displayName": "上一低点位置",
    "description": "上一低点位置",
    "usage": "LLVBARS(X,N) 求N周期内X最低值到当前周期数,N=0表示从第一个有效值开始统计。",
    "params": [
      "X",
      "N"
    ],
    "examples": [
      "LLVBARS(HIGH,20) 求得20日最低点到当前的周期数。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "LN",
    "category": "math",
    "displayName": "自然对数",
    "description": "自然对数",
    "usage": "LN(X) 以e为底的对数。",
    "params": [
      "X"
    ],
    "examples": [
      "LN(CLOSE) 求收盘价的对数。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "LOG",
    "category": "math",
    "displayName": "对数",
    "description": "对数",
    "usage": "LOG(X) 取得X的对数。",
    "params": [
      "X"
    ],
    "examples": [
      "LOG(100) 等于2。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "LONGCROSS",
    "category": "logic",
    "displayName": "维持一定周期后上穿",
    "description": "维持一定周期后上穿",
    "usage": "LONGCROSS(A,B,N) 表示A在N周期内都小于B,本周期从下方向上穿过B时返回1,否则返回0。",
    "params": [
      "A",
      "B",
      "N"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "LOW",
    "category": "market",
    "displayName": "最低价",
    "description": "最低价",
    "usage": "LOW",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "LWINNER",
    "category": "pattern",
    "displayName": "近期获利盘比例",
    "description": "近期获利盘比例",
    "usage": "LWINNER(5,CLOSE) 表示最近5天的那部分成本以当前收市价卖出的获利盘比例。例如返回0.1表示10%获利盘。",
    "params": [
      "5",
      "CLOSE"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "MA",
    "category": "reference",
    "displayName": "简单移动平均",
    "description": "简单移动平均",
    "usage": "MA(X,M) X的M日简单移动平均。",
    "params": [
      "X",
      "M"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "MAX",
    "category": "arithmetic",
    "displayName": "较大值",
    "description": "较大值",
    "usage": "MAX(A,B) 返回A和B中的较大值。",
    "params": [
      "A",
      "B"
    ],
    "examples": [
      "MAX(CLOSE-OPEN,0) 表示若收盘价大于开盘价返回它们的差值,否则返回0。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "MEMA",
    "category": "reference",
    "displayName": "平滑移动平均",
    "description": "平滑移动平均",
    "usage": "MEMA(X,M) X的M日平滑移动平均。",
    "params": [
      "X",
      "M"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "MIN",
    "category": "arithmetic",
    "displayName": "较小值",
    "description": "较小值",
    "usage": "MIN(A,B) 返回A和B中的较小值。",
    "params": [
      "A",
      "B"
    ],
    "examples": [
      "MIN(CLOSE,OPEN) 返回开盘价和收盘价中的较小值。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "MINUTE",
    "category": "time",
    "displayName": "分钟",
    "description": "分钟",
    "usage": "MINUTE 函数返回有效值范围为(0-59),对于日线及更长的分析周期值为0。",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "MONTH",
    "category": "time",
    "displayName": "月份",
    "description": "月份",
    "usage": "MONTH 函数返回有效值范围为(1-12)。",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "NDAY",
    "category": "logic",
    "displayName": "连大",
    "description": "连大",
    "usage": "NDAY(CLOSE,OPEN,3) 表示连续3日收阳线。",
    "params": [
      "CLOSE",
      "OPEN",
      "3"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "NOT",
    "category": "arithmetic",
    "displayName": "取反",
    "description": "取反",
    "usage": "NOT(X) 返回非X,即当X=0时返回1,否则返回0。",
    "params": [
      "X"
    ],
    "examples": [
      "NOT(ISUP) 表示平盘或收阴。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "O",
    "category": "market",
    "displayName": "开盘价",
    "description": "开盘价",
    "usage": "O",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "OPEN",
    "category": "market",
    "displayName": "开盘价",
    "description": "开盘价",
    "usage": "OPEN",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "PEAK",
    "category": "pattern",
    "displayName": "波峰值",
    "description": "波峰值",
    "usage": "PEAK(K,N,M) 表示之字转向ZIG(K,N)的前M个波峰的数值,M必须大于等于1。",
    "params": [
      "K",
      "N",
      "M"
    ],
    "examples": [
      "PEAK(1,5,1) 表示%5最高价ZIG转向的上一个波峰的数值。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "PEAKBARS",
    "category": "pattern",
    "displayName": "波峰位置",
    "description": "波峰位置",
    "usage": "PEAKBARS(K,N,M) 表示之字转向ZIG(K,N)的前M个波峰到当前的周期数,M必须大于等于1。",
    "params": [
      "K",
      "N",
      "M"
    ],
    "examples": [
      "PEAKBARS(0,5,1) 表示%5开盘价ZIG转向的上一个波峰到当前的周期数。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "PERIOD",
    "category": "time",
    "displayName": "周期",
    "description": "当前分析周期。",
    "usage": "PERIOD",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "PLOYLINE",
    "category": "drawing",
    "displayName": "折线段",
    "description": "折线段",
    "usage": "PLOYLINE(COND,PRICE),当COND条件满足时,以PRICE位置为顶点画折线连接。",
    "params": [
      "COND",
      "PRICE"
    ],
    "examples": [
      "PLOYLINE(HIGH>=HHV(HIGH,20),HIGH)表示在创20天新高点之间画折线。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "POINTDOT",
    "category": "drawProperty",
    "displayName": "画小圆点线",
    "description": "画小圆点线",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "POW",
    "category": "math",
    "displayName": "乘幂",
    "description": "乘幂",
    "usage": "POW(A,B) 返回A的B次幂。",
    "params": [
      "A",
      "B"
    ],
    "examples": [
      "POW(CLOSE,3) 求得收盘价的3次方。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "PPART",
    "category": "pattern",
    "displayName": "远期成本分布比例",
    "description": "远期成本分布比例",
    "usage": "PPART(10),表示10前的成本占总成本的比例,0.2表示20%。",
    "params": [
      "10"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "PWINNER",
    "category": "pattern",
    "displayName": "远期获利盘比例",
    "description": "远期获利盘比例",
    "usage": "PWINNER(5,CLOSE) 表示5天前的那部分成本以当前收市价卖出的获利盘比例。例如返回0.1表示10%获利盘。",
    "params": [
      "5",
      "CLOSE"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "RANGE",
    "category": "reference",
    "displayName": "介于某个范围之间",
    "description": "介于某个范围之间",
    "usage": "RANGE(A,B,C) A在B和C。",
    "params": [
      "A",
      "B",
      "C"
    ],
    "examples": [
      "RANGE(A,B,C)表示A大于B同时小于C时返回1,否则返回0。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "REF",
    "category": "reference",
    "displayName": "向前引用",
    "description": "向前引用",
    "usage": "REF(X,A) 引用A周期前的X值。",
    "params": [
      "X",
      "A"
    ],
    "examples": [
      "REF(CLOSE,1) 表示上一周期的收盘价,在日线上就是昨收。",
      "REF(CLOSE,20011208) 表示2001年12月08日的收盘价。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "REFDATE",
    "category": "reference",
    "displayName": "指定引用",
    "description": "指定引用",
    "usage": "REFDATE(X,A) 引用A日期的X值。",
    "params": [
      "X",
      "A"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "REVERSE",
    "category": "reference",
    "displayName": "求相反数",
    "description": "求相反数",
    "usage": "REVERSE(X) 返回-X。",
    "params": [
      "X"
    ],
    "examples": [
      "REVERSE(CLOSE) 返回-CLOSE。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "RGB",
    "category": "colorFunction",
    "displayName": "RGB 颜色函数",
    "description": "按函数参数指定颜色。",
    "usage": "RGB(R,G,B)",
    "params": [
      "R",
      "G",
      "B"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "ROUND2",
    "category": "math",
    "displayName": "四舍五入",
    "description": "按指定精度四舍五入。",
    "usage": "ROUND2(X,N)",
    "params": [
      "X",
      "N"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "SAR",
    "category": "pattern",
    "displayName": "抛物转向",
    "description": "抛物转向",
    "usage": "SAR(N,S,M),N为计算周期,S为步长,M为极值。",
    "params": [
      "N",
      "S",
      "M"
    ],
    "examples": [
      "SAR(10,2,20) 表示计算10日抛物转向,步长为2%,极限值为20%。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "SARTURN",
    "category": "pattern",
    "displayName": "抛物转向点",
    "description": "抛物转向点",
    "usage": "SARTURN(N,S,M) N为计算周期,S为步长,M为极值,若发生向上转向则返回1,若发生向下转向则返回-1,否则为0。",
    "params": [
      "N",
      "S",
      "M"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "SELLVOL",
    "category": "market",
    "displayName": "主动性卖盘",
    "description": "主动性卖盘",
    "usage": "SELLVOL 当本笔成交为主动性卖盘时,其数值等于成交量,否则为0。",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "SETCODE",
    "category": "market",
    "displayName": "市场代码",
    "description": "市场或交易所代码。",
    "usage": "SETCODE",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "SIN",
    "category": "math",
    "displayName": "正弦",
    "description": "正弦",
    "usage": "SIN(X) 返回X的正弦值。",
    "params": [
      "X"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "SLOPE",
    "category": "statistics",
    "displayName": "线性回归斜率",
    "description": "线性回归斜率",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "SMA",
    "category": "reference",
    "displayName": "累积平均",
    "description": "累积平均",
    "usage": "SMA(X,N,M) X的M日累积平均,M为权重,如Y=(X*M+Y'*(N-M))/N",
    "params": [
      "X",
      "N",
      "M"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "SQRT",
    "category": "math",
    "displayName": "开方",
    "description": "开方",
    "usage": "SQRT(X)  求X的平方根。",
    "params": [
      "X"
    ],
    "examples": [
      "SQRT(CLOSE) 收盘价的平方根。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "STD",
    "category": "statistics",
    "displayName": "估算标准差",
    "description": "估算标准差",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "STDP",
    "category": "statistics",
    "displayName": "总体标准差",
    "description": "总体标准差",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "STICK",
    "category": "drawProperty",
    "displayName": "画柱状线",
    "description": "画柱状线",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "STICKLINE",
    "category": "drawing",
    "displayName": "绘制柱线",
    "description": "绘制柱线",
    "usage": "STICKLINE(COND,PRICE1,PRICE2,WIDTH,EMPTY),当COND条件满足时,在PRICE1和PRICE2位置之间画柱状线,宽度为WIDTH(10为标准间距),EMPTH不为0则画空心柱。",
    "params": [
      "COND",
      "PRICE1",
      "PRICE2",
      "WIDTH",
      "EMPTY"
    ],
    "examples": [
      "STICKLINE(CLOSE>OPEN,CLOSE,OPEN,0.8,1)表示画K线中阳线的空心柱体部分。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "STRCAT",
    "category": "string",
    "displayName": "字符串拼接",
    "description": "拼接两个字符串。",
    "usage": "STRCAT(A,B)",
    "params": [
      "A",
      "B"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "SUM",
    "category": "reference",
    "displayName": "总和",
    "description": "总和",
    "usage": "SUM(X,N) 统计N周期中X的总和,N=0则从第一个有效值开始。",
    "params": [
      "X",
      "N"
    ],
    "examples": [
      "SUM(VOL,0) 表示统计从上市第一天以来的成交量总和。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "SUMBARS",
    "category": "reference",
    "displayName": "累加到指定值的周期数",
    "description": "累加到指定值的周期数",
    "usage": "SUMBARS(X,A) 将X向前累加直到大于等于A,返回这个区间的周期数。",
    "params": [
      "X",
      "A"
    ],
    "examples": [
      "SUMBARS(VOL,CAPITAL) 求完全换手到现在的周期数。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "TAN",
    "category": "math",
    "displayName": "正切",
    "description": "正切",
    "usage": "TAN(X) 返回X的正切值。",
    "params": [
      "X"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "TIME",
    "category": "time",
    "displayName": "时间",
    "description": "时间",
    "usage": "TIME 函数返回有效值范围为(000000-235959)。",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "TOTALCAPITAL",
    "category": "market",
    "displayName": "总股本",
    "description": "总股本，常用于换手率和股本口径计算。",
    "usage": "TOTALCAPITAL",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "TROUGH",
    "category": "pattern",
    "displayName": "波谷值",
    "description": "波谷值",
    "usage": "TROUGH(K,N,M) 表示之字转向ZIG(K,N)的前M个波谷的数值,M必须大于等于1。",
    "params": [
      "K",
      "N",
      "M"
    ],
    "examples": [
      "TROUGH(2,5,2) 表示%5最低价ZIG转向的前2个波谷的数值。",
      "TROUGH(2,5,2) 表示%5最低价ZIG转向的前2个波谷到当前的周期数。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "TROUGHBARS",
    "category": "pattern",
    "displayName": "波谷位置",
    "description": "波谷位置",
    "usage": "TROUGHBARS(K,N,M) 表示之字转向ZIG(K,N)的前M个波谷到当前的周期数,M必须大于等于1。",
    "params": [
      "K",
      "N",
      "M"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "UPNDAY",
    "category": "logic",
    "displayName": "连涨",
    "description": "连涨",
    "usage": "UPNDAY(CLOSE,M) 表示连涨M个周期。",
    "params": [
      "CLOSE",
      "M"
    ],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "V",
    "category": "market",
    "displayName": "成交量",
    "description": "成交量",
    "usage": "V",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "VALUEWHEN",
    "category": "reference",
    "displayName": "条件取值",
    "description": "条件成立时取指定表达式的值。",
    "usage": "VALUEWHEN(COND,VALUE)",
    "params": [
      "COND",
      "VALUE"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  },
  {
    "name": "VAR",
    "category": "statistics",
    "displayName": "估算样本方差",
    "description": "估算样本方差",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "VARP",
    "category": "statistics",
    "displayName": "总体样本方差",
    "description": "总体样本方差",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "VOL",
    "category": "market",
    "displayName": "成交量",
    "description": "成交量",
    "usage": "VOL",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "VOLSTICK",
    "category": "drawProperty",
    "displayName": "画彩色柱状线",
    "description": "画彩色柱状线",
    "usage": "",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "WEEK",
    "category": "time",
    "displayName": "星期",
    "description": "星期",
    "usage": "WEEK 函数返回有效值范围为(0-6),0表示星期天。",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "WINNER",
    "category": "pattern",
    "displayName": "获利盘比例",
    "description": "获利盘比例",
    "usage": "WINNER(CLOSE) 表示以当前收市价卖出的获利盘比例。",
    "params": [
      "CLOSE"
    ],
    "examples": [
      "返回0.1表示10%获利盘,WINNER(10.5)表示10.5元价格的获利盘比例。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "YEAR",
    "category": "time",
    "displayName": "年份",
    "description": "年份",
    "usage": "YEAR",
    "params": [],
    "examples": [],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "ZIG",
    "category": "pattern",
    "displayName": "之字转向",
    "description": "之字转向",
    "usage": "ZIG(K,N) 当价格变化量超过N%时转向,K表示0:开盘价,1:最高价,2:最低价,3:收盘价,其余:数组信息",
    "params": [
      "K",
      "N"
    ],
    "examples": [
      "ZIG(3,5) 表示收盘价的5%的ZIG转向。"
    ],
    "aliases": [],
    "source": "通达信函数参考.txt",
    "confidence": "high"
  },
  {
    "name": "ZTPRICE",
    "category": "reference",
    "displayName": "涨停价",
    "description": "按昨收与涨停幅度计算理论涨停价。",
    "usage": "ZTPRICE(PRICE,RATIO)",
    "params": [
      "PRICE",
      "RATIO"
    ],
    "examples": [],
    "aliases": [],
    "source": "manual",
    "confidence": "manual"
  }
];
