export const initialTdx = `{ TDX Editor 示例公式 }
主力:=EMA(CLOSE,13);
趋势:=IF(CLOSE>REF(CLOSE,1),1,0);
量能:=VOL/MA(VOL,5);

金线:MA(CLOSE,5),COLOR00D7FF,LINETHICK2;
慢线:MA(CLOSE,20),COLORCYAN;
DRAWICON(CROSS(金线,慢线),LOW,1),COLORRED;
STICKLINE(趋势=1,OPEN,CLOSE,2,0),COLORLIRED;
STICKLINE(趋势=0,OPEN,CLOSE,2,0),COLORLIGREEN;
`
